print("JARO:")
print("MARTHA x MARHTA: ", jaro_dist('MARTHA', 'MARHTA')) // 0.944...
print("DIXON x DICKSONX: ", jaro_dist('DIXON', 'DICKSONX')) // 0.766...
print("CRATE x TRACE: ", jaro_dist('CRATE', 'TRACE')) // 0.733...
print("hello x hello: ", jaro_dist('hello', 'hello')) // 1.0